apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1
managedNodeGroups:
  - name: cluster
    instanceType: m5.large
    desired Capasity: 3
    spot: true



    
  